version: '3'
services:
  mysql:
    image: mysql:8
    container_name: ra_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: books
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: ra_elasticsearch
    #ports:
      #- 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: ra_kibana
    environment:
      - "ELASTCISEARCH_URL=http://localhost:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
     - elasticsearch                 
  logstash:
    build: 
      context: .
      dockerfile: Dockerfile-logstash
    container_name: ra_logstash
    environment:
      - logging.level=debug
    depends_on:
      - mysql
      - elasticsearch
    volumes:
      - ./volumes/logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./volumes/logstash/config/pipeline.yml:/usr/share/logstash/config/pipeline.yml
      - ./volumes/logstash/config/queries/:/usr/share/logstash/config/queries/  