version: '3.8'

services:
   mysql:
      image: mysql:8.0
      ports:
         - 3307:3306
      environment:
         - MYSQL_ROOT_PASSWORD=admin
         - MYSQL_DATABASE=servicedb
         - MYSQL_USER=admin
         - MYSQL_PASSWORD=admin
      volumes:
         - mysql_data:/var/lib/mysql
      networks:
         - logstash_network
   logstash:
      build: ./logstash
      image: docker.elastic.co/logstash/logstash:7.9.3
      environment:
         - LOGSTASH_JDBC_URL=jdbc:mysql://mysql:3037/servicedb?useSSL=false
         - LOGSTASH_JDBC_DRIVER=com.mysql.jdbc.Driver
         - LOGSTASH_JDBC_DRIVER_JAR_LOCATION=mysql-connector-java.jar
         - LOGSTASH_JDBC_USERNAME=admin
         - LOGSTASH_JDBC_PASSWORD=admin
      ports:
         - 9600:9600
         - 5044:5044
      networks:
         - logstash_network
      volumes:
         - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
         - ./logstash/sample.log:/usr/share/logstash/pipeline/sample.log
      depends_on:
         - mysql
         - elasticsearch
   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - transport.host=127.0.0.1
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - logstash_network
volumes:
   elasticsearch_data:
   mysql_data:
networks:
   logstash_network:
